FROM husarion/rosbot-xl-gazebo:humble-0.9.1-20240131

USER root

RUN rm -f /etc/apt/sources.list.d/ros2*.list

RUN echo "deb [trusted=yes] http://packages.ros.org/ros2/ubuntu jammy main" > /etc/apt/sources.list.d/ros2.list

RUN apt-get update --allow-insecure-repositories || true
RUN apt-get install -y --allow-unauthenticated \
    ros-humble-nav2-msgs \
    ros-humble-rclcpp-action \
    && rm -rf /var/lib/apt/lists/*